# Generated by Django 5.2.6 on 2025-09-07 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id_autor', models.AutoField(db_column='T001IdPersona', editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='T001Nombre', max_length=100)),
                ('apellido', models.CharField(db_column='T001Apellido', max_length=100)),
                ('biografia', models.TextField(db_column='T001Biografia')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'db_table': 'T001Autor',
            },
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id_editorial', models.AutoField(db_column='T002IdEditorial', editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='T002Nombre', max_length=100)),
                ('direccion', models.CharField(db_column='T002Direccion', max_length=100)),
                ('telefono', models.CharField(db_column='T002Telefono', max_length=100)),
            ],
            options={
                'verbose_name': 'Editorial',
                'verbose_name_plural': 'Editoriales',
                'db_table': 'T002Editorial',
            },
        ),
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id_miembro', models.AutoField(db_column='T004IdMiembro', editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='T004Nombre', max_length=100)),
                ('apellido', models.CharField(db_column='T004Apellido', max_length=100)),
                ('email', models.EmailField(db_column='T004Email', max_length=100)),
                ('fecha_membresia', models.DateField(db_column='T004FechaMembresia')),
            ],
            options={
                'verbose_name': 'Miembro',
                'verbose_name_plural': 'Miembros',
                'db_table': 'T004Miembro',
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id_libro', models.AutoField(db_column='T003IdLibro', editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(db_column='T003Titulo', max_length=100)),
                ('resumen', models.TextField(db_column='T003Resumen')),
                ('isbn', models.CharField(db_column='T003ISBN', max_length=100, unique=True)),
                ('anio_publicacion', models.PositiveIntegerField(db_column='T003AnioPublic', default=0)),
                ('autor', models.ForeignKey(db_column='T003AutorId', on_delete=django.db.models.deletion.CASCADE, related_name='libros', to='api_parcial.autor')),
                ('editorial', models.ForeignKey(db_column='T003EditorialId', on_delete=django.db.models.deletion.CASCADE, related_name='libros', to='api_parcial.editorial')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'db_table': 'T003Libro',
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id_prestamo', models.AutoField(db_column='T005IdPrestamo', editable=False, primary_key=True, serialize=False)),
                ('fecha_prestamo', models.DateField(db_column='T005FechaPrestamo')),
                ('fecha_devolucion', models.DateField(blank=True, db_column='T005FechaDevolucion', null=True)),
                ('libro', models.ForeignKey(db_column='T005LibroId', on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='api_parcial.libro')),
                ('miembro', models.ForeignKey(db_column='T005MiembroId', on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='api_parcial.miembro')),
            ],
            options={
                'verbose_name': 'Prestamo',
                'verbose_name_plural': 'Prestamos',
                'db_table': 'T005Prestamo',
            },
        ),
    ]
